### ISSUE TITLE
Update documentation on mappings

### ISSUE THREAD

**Issue by reubano** [reubano/csv2ofx#16]
The readme documentation is outdated, e.g., `type` should be either `debit` or `credit`.

**Comment by xtiansimon** [comment]
I'm new to OFX, so please forgive my naivete if I miss the big picture because of the examples I've been exposed to. It's not clear to me which _keys_ of the mapping file refer to which _structures_ in an OFX file. 
Specifically, the OFX file structure which I've encountered (from CapitalOne, Chase, and Citibank checking and CapitalOne, Chase, and Amex credit cards) has three parts: header, transactions, footer. The CSV file I'm working to convert would represent only the transactions part.
Specifically in the documentation,
> "The mapping object consists of a dictionary whose keys are OFX/QIF attributes and whose values are functions which should return the corresponding value from a record (csv row)." 
It's a little nit, but from accounting I associate "records" as a whole with documents. The OFX file as a record contains all three parts and this term seems to refer to the whole document. Then the parenthetical "(csv row)" suggests a specific concern with transactions. And the keys don't clarify this ambiguity.
This gets to a question. Which features of the mapping file are required by csv2ofx to construct a complete OFX file, and which features are required columns in the csv file export from the bank (to be sure I have a file csv2ofx is capable of converting)?

**Comment by reubano** [comment]
> I find banks refer to 'transactions'. In the mixed context of the XML specification (header, transactions, footer) what is a record? Is it the whole XML? Or an individual transaction?

an individual transaction

> where would does account number come from

https://github.com/reubano/csv2ofx/blob/6d35d306f54cbe8a250cae71e51a7fe82665680d/csv2ofx/__init__.py#L261
